USE [master]
GO

CREATE DATABASE MECANIC 
GO
USE MECANIC

--CRIAÇÃO DAS TABELAS

CREATE TABLE dbo.CLIENTE
(
	COD_CLIENTE NUMERIC(18,0) IDENTITY(1,1) PRIMARY KEY NOT NULL,
	RG VARCHAR(9) NOT NULL,
	CPF NUMERIC(30) NULL,
	NOME VARCHAR(50) NOT NULL,
	ENDERECO VARCHAR(50) NULL,
	CEP NUMERIC(30) NULL,
	CIDADE VARCHAR(30) NULL, 
	ESTADO CHAR(2) NOT NULL,
	TELEFONE VARCHAR(15) NULL
	
)

CREATE TABLE dbo.AUTOMOVEL
(
	COD_AUTOMOVEL NUMERIC(10,0) IDENTITY(1,1) NOT NULL,
	COD_CLIENTE NUMERIC(18) NOT NULL,
	MARCA VARCHAR(30) NOT NULL,
	MODELO VARCHAR(30) NOT NULL,
	ANO NUMERIC(4) NULL,
	CONSTRAINT PK_AUTOMOVEL_CLIENTE PRIMARY KEY(COD_AUTOMOVEL)
)

CREATE TABLE dbo.PECA_SERVICO
(
	COD_PECA_SERVICO NUMERIC(18,0) IDENTITY(1,1) PRIMARY KEY NOT NULL,
	PECA VARCHAR(30) NULL,
	SERVICO VARCHAR(30) NOT NULL,
	VALOR FLOAT NOT NULL
)

CREATE TABLE dbo.MANUTENCAO
(
	COD_MANUTENCAO NUMERIC(18,0) IDENTITY(1,1) NOT NULL,
	COD_AUTOMOVEL NUMERIC(10) NOT NULL,
	SOLICITACAO VARCHAR(100) NOT NULL,
	OBS	VARCHAR(100) NULL,
	DATA_INI DATETIME NOT NULL,
	DATA_FIM DATETIME NULL,
	CONSTRAINT PK_MANUTENCAO_AUTOMOVEL PRIMARY KEY(COD_MANUTENCAO)
)


CREATE TABLE dbo.MANUTENCAO_SERVICO
(
	COD_MANUTENCAO_SERVICO NUMERIC(18,0) IDENTITY(1,1) NOT NULL,
	COD_PECA_SERVICO NUMERIC(18) NOT NULL,
	COD_MANUTENCAO NUMERIC(18) NOT NULL,
	VALOR FLOAT NOT NULL,
	CONSTRAINT PK_MANUTENCAO_PECA_SERVICO PRIMARY KEY(COD_MANUTENCAO_SERVICO)
)


--CRIAÇÃO DOS RELACIONAMENTOS 
--AUTOMOVEL_CLIENTE
ALTER TABLE dbo.AUTOMOVEL WITH CHECK ADD CONSTRAINT FK_AUTOMOVEL_CLIENTE FOREIGN KEY (COD_CLIENTE)
REFERENCES dbo.CLIENTE(COD_CLIENTE)
GO

ALTER TABLE dbo.AUTOMOVEL CHECK CONSTRAINT FK_AUTOMOVEL_CLIENTE
GO


-- MANUTENCAO - AUTOMOVEL
ALTER TABLE dbo.MANUTENCAO WITH CHECK ADD CONSTRAINT FK_MANUTENCAO_AUTOMOVEL FOREIGN KEY (COD_AUTOMOVEL)
REFERENCES dbo.AUTOMOVEL(COD_AUTOMOVEL)
GO

ALTER TABLE dbo.MANUTENCAO CHECK CONSTRAINT FK_MANUTENCAO_AUTOMOVEL 
GO

--MANUTENCAO_SERVICO - PECA_SERVICO
ALTER TABLE dbo.MANUTENCAO_SERVICO WITH CHECK ADD CONSTRAINT FK_MANUTENCAO_PECA_SERVICO FOREIGN KEY (COD_PECA_SERVICO)
REFERENCES dbo.PECA_SERVICO(COD_PECA_SERVICO)
GO

ALTER TABLE dbo.MANUTENCAO_SERVICO CHECK CONSTRAINT FK_MANUTENCAO_PECA_SERVICO 
GO

--MANUTENCAO_SERVICO - MANUTENCAO
ALTER TABLE dbo.MANUTENCAO_SERVICO WITH CHECK ADD CONSTRAINT FK_MANUTENCAO_PECA_SERVICOS FOREIGN KEY (COD_MANUTENCAO)
REFERENCES dbo.MANUTENCAO(COD_MANUTENCAO)
GO

ALTER TABLE dbo.MANUTENCAO_SERVICO CHECK CONSTRAINT FK_MANUTENCAO_PECA_SERVICOS 
GO

-- INSERÇÕES NAS TABELAS
--CLIENTE
INSERT INTO dbo.CLIENTE VALUES ('458899444',258963210520,'João da Silva','Benedito Oliveira Soares',18185000,'Pilar do Sul','SP','15920009166')
INSERT INTO dbo.CLIENTE VALUES ('158899222',153963190000,'Maria do Rosário Silva','Jose Bezerra',12185222,'São Roque','SP','159255531202')
INSERT INTO dbo.CLIENTE VALUES ('958896440',123453210660,'Mario Garcia','São João Jr',10180000,'Itapetininga','SP','15997435601')
INSERT INTO dbo.CLIENTE VALUES ('858811474',285293210531,'Juan Bernado Silverio','Getúlio Vargas',00000000,'Sorocaba','SP','15991189587')

--AUTOMOVEL
INSERT INTO dbo.AUTOMOVEL VALUES (1,'Fiat','Uno',NULL)
INSERT INTO dbo.AUTOMOVEL VALUES (2,'Nissan', 'Versa',NULL)
INSERT INTO dbo.AUTOMOVEL VALUES (3,'Fiat', 'Palio',NULL)
INSERT INTO dbo.AUTOMOVEL VALUES (4,'Chevrolet', 'Corsa',NULL)


--PECASERVICO
INSERT INTO dbo.PECA_SERVICO VALUES ('Parafuso XYZ','Troca parafuso',1.5)
INSERT INTO dbo.PECA_SERVICO VALUES ('Filtro de ar-condicionado XXX','Troca Filtro',35.69)
INSERT INTO dbo.PECA_SERVICO VALUES ('Vela ZZZXY','Troca Vela',15.89)
INSERT INTO dbo.PECA_SERVICO VALUES ('','Limpeza',25.50)
INSERT INTO dbo.PECA_SERVICO VALUES ('','Troca Pneu',10.00)
INSERT INTO dbo.PECA_SERVICO VALUES ('','Revisão Geral',20.60)

--MANUTENCAO
INSERT INTO dbo.MANUTENCAO VALUES (1,'Carro está muito sujo','','2022-01-02 00:00:00.000','2022-01-10 00:00:00.000')
INSERT INTO dbo.MANUTENCAO VALUES (2,'Motor batendo','Sem comentários','2022-10-02 00:00:00.000','')
INSERT INTO dbo.MANUTENCAO VALUES (1,'Pneu Furado','','2022-01-02 00:00:00.000','2022-01-10 00:00:00.000')

--MANUTENCAO_SERVICO
INSERT INTO dbo.MANUTENCAO_SERVICO VALUES (4,7,25.50)
INSERT INTO dbo.MANUTENCAO_SERVICO VALUES (5,2,10)
INSERT INTO dbo.MANUTENCAO_SERVICO VALUES (6,3,20.60)